server:
  port: 8080

spring:
  application:
    name: task-monitoring
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/batch_monitoring?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ganzhou.monitoring.entity,com.ganzhou.monitoring.dto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

monitor:
  scheduler:
    db-lock-enabled: true
    db-lock-timeout-seconds: 0
